### ISSUE TITLE
Great Tool, Can we add ability to pass collection and return the count of the collection 

### ISSUE THREAD

**Issue by Otienoh** [techouse/total-records#2]
Right, now the tool works great. Maybe we could add the ability to pass a collection in the first parameter instead of only the class/model. That way we can return the count of the model with scope and where clauses applied to it.

i.e.
```
// Package supports this

new TotalRecords(User::class, 'Total Registered Users'),

// Use case could be

new TotalRecords(User::activeUsers(), 'Total Registered Users'),

// or

new TotalRecords(User::activeUsers()->get(), 'Total Registered Users'),

```

**Comment by Otienoh** [comment]
Just noticed this is a different use case. The package focuses on returning simple count() of the model class. To achieve the above I used the default Nova value metric and manually provided the final values to the metric using the `result` and `previous` methods:

```
return $this->result(User::activeUsers()->count());
```

Thanks for the package @techouse 👍

**Comment by techouse** [comment]
Glad it worked out for you :)
