### ISSUE TITLE
H1 tags to H2 tags

### ISSUE THREAD

**Issue by Milkhan** [techouse/total-records#3]
Thank you for the nice tool! 
Can you please change the H1 tag to H2 please on the Card.vue file. When one has multiple cards on the page, it gets multiple H1 tags and it is not a good practice to have more then one H1 tag in Html as you know. 
Thank you!

**Comment by techouse** [comment]
Good thinking! Will get straight on it :)

**Comment by techouse** [comment]
Fixed.
