### ISSUE TITLE
Class does not exist?

### ISSUE THREAD

**Issue by techn0guy** [techouse/total-records#4]
Hello, I just installed this card and every model I try is coming up as "Class does not exist!". 

I know that these models exist, I tried with something as basic as the user model:

`new TotalRecords(\App\User::class), `

The endpoint it tries to get is /nova-vendor/total-records/endpoint?model=App%255CUser

I've tried App\User  as well, but still nothing

**Comment by techn0guy** [comment]
I just pushed the code to my staging server and it miraculously works fine, it's strangely not working on my local dev environment.

**Comment by techouse** [comment]
Hmm, idk. I never observed anything like it. Try clearing your caches and stuff.

**Comment by techn0guy** [comment]
After further investigation, it seems like the models pathway isn't translating correctly. If I bypass the validation and dump the $model variable it shows: App%5CModels%5CCrystal

Should'nt the %5C's be converted to slashes?

**Comment by techouse** [comment]
Hmm weird behaviour. Calling the static `class` method on any class will just get its fully qualified name and I honestly have no clue why it's giving you this headache. Try and use it in a vanilla Laravel Nova app and see if you get the same results.

**Comment by techn0guy** [comment]
I was able to fix this by placing 
`$model = str_replace("%5C", "\\", $model);`
right after
`$model = $request->input('model');`
in the TotalRecordsController.php

In your environment, when it posts data, does the URL look like this? /nova-vendor/total-records/endpoint?model=App%255CUser

**Comment by techouse** [comment]
@abhishekbhardwaj thanx for your fix 🙏

**Comment by mohamedyasser** [comment]
still not working you need to decode model before validation

**Comment by mjlandicho** [comment]
Still not working for me, same issues

**Comment by techouse** [comment]
Will look into it 🔍

**Comment by techouse** [comment]
[Fixed](https://github.com/techouse/total-records/commit/949a19155d425854675caa39cf24ceb56d4d50d9)
